<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
$uid = $grid->getUid();
?>
<div class="clearfix" data-spy="grid" data-grid="<?= $uid ?>">
  <script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
  </script>

  <nav class="navbar navbar-light bg-light justify-content-start">
    <a href="<?= $grid->filter('amount', 'eq', '', true) ?>"
       class="btn <?= (null === $grid->getFilter('amount', 'eq') ? 'btn-info' : 'btn-secondary') ?>" data-ajax>
        <?= __('All') ?>
    </a>
    <a href="<?= $grid->filter('amount', 'eq', 0, false) ?>"
       class="ml-2 btn <?= (0 === $grid->getFilter('amount', 'eq') ? 'btn-info' : 'btn-secondary') ?>" data-ajax>
        <?= __('Zero') ?>
    </a>
  </nav>
  <hr/>

    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th><?=__('User')?></th>
      <th width="180px"><a href="<?=$grid->order('amount')?>"><?=__('Balance')?></a></th>
      <th width="320px"></th>
      <th width="180px"><a href="<?=$grid->order('created')?>"><?=__('Created')?></a></th>
      <th width="120px"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $i => $row) : $user = $row->getRelation('Users'); ?>
      <tr>
        <td><a href="<?=$this->url('users', 'profile', ['id' => $user->id])?>"><?= $user->login ?></a></td>
        <td><?= $row->amount ?></td>
        <td>
          <form action="<?= $this->url('wallet', 'send') ?>" class="form-inline" data-ajax method="post">
            <input type="hidden" name="id" value="<?=$user->id?>" />
            <label>
              <input name="amount" value="0" class="form-control" />
            </label>
            <button type="submit" class="btn btn-primary"><?=__('Send')?></button>
          </form>
        </td>
        <td><?= $row->created ?></td>
        <td class="controls">
          <a href="<?= $this->url('users', 'profile', ['id' => $user->id]); ?>" class="btn btn-info"
             data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
            <i class="fa fa-id-card"></i>
          </a>
          <a href="<?=$this->url('wallet', 'transactions', ['transactions-filter-userId' => $user->id])?>" class="btn btn-primary">
            <i class="fa fa-exchange"></i>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

    <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

</div>