<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
$uid = $grid->getUid();
?>
<div class="clearfix" data-spy="grid" data-grid="<?= $uid ?>">
  <script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
  </script>

  <nav class="navbar navbar-light bg-light justify-content-start">
    <a href="<?= $grid->filter('amount', 'eq', '', true) ?>"
       class="btn <?= (null === $grid->getFilter('amount', 'eq') ? 'btn-info' : 'btn-secondary') ?>" data-ajax>
        <?= __('All') ?>
    </a>
    <a href="<?= $grid->filter('amount', 'eq', 0, false) ?>"
       class="ml-2 btn <?= (0 === $grid->getFilter('amount', 'eq') ? 'btn-info' : 'btn-secondary') ?>" data-ajax>
        <?= __('Zero') ?>
    </a>
  </nav>
  <hr/>

    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th width="60px" class="text-center"><a href="<?= $grid->order('users.id') ?: '#' ?>"><?= __('Id') ?></a></th>
      <th width="180px"><a href="<?= $grid->order('users.login') ?: '#' ?>"><?= __('User') ?></a></th>
      <th class="text-center"><a href="<?=$grid->order('amount')?>"><?=__('Balance')?></a></th>
      <th class="text-center"><a href="<?=$grid->order('blocked')?>"><?=__('Blocked')?></a></th>
      <th width="380px"></th>
      <th width="200px"><a href="<?=$grid->order('created')?>"><?=__('Created')?></a></th>
      <th width="120px"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $i => $row) :  $user = $row->getRelation('Users'); ?>
      <tr>
        <td class="text-right"><?= $row->userId ?></td>
        <td>
          <a href="<?=$this->url('users', 'profile', ['id' => $row->userId])?>"
               data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
                <?= $row->login ?>
          </a>
        </td>
        <td class="text-center"><?= $row->amount ?></td>
        <td class="text-center"><?= $row->blocked ?></td>
        <td>
          <form action="<?= $this->url('wallet', 'send') ?>" class="form" data-ajax method="post">
            <input type="hidden" name="id" value="<?=$row->userId?>" />
            <div class="form-row">
              <label class="col-4">
                <input type="number" min="0" max="1000000" name="amount" value="0" class="form-control" />
              </label>
              <div class="col-4">
                <button type="submit" class="btn btn-primary"><?=__('Send')?></button>
              </div>
            </div>
          </form>
        </td>
        <td><?= $row->created ?></td>
        <td class="controls d-flex justify-content-around">
          <a href="<?=$this->url('wallet', 'transactions', ['transactions-filter-user' => $user->id])?>" class="btn btn-warning">
            <i class="fas fa-exchange-alt"></i>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

    <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

</div>