<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
$uid = $grid->getUid();

use \Application\Transactions\Table;
?>


<?php
/** @var \Bluz\View\View $this */ ?>
<?php
$uid = uniqid('form_', false); ?>
<div class="card text-center">
    <?php
    require_once __DIR__ . '/../../users/views/partial/card-header.phtml' ?>
    <div class="card-body">
        <h4 class="card-title"><?= __('Wallet') ?></h4>
        <div class="card center">
            <div class="card-body">

                <div class="clearfix" data-spy="grid" data-grid="<?= $uid ?>">
                    <script>
                      // use data-spy="grid" for use AJAX for reload grid
                      require(['bluz.grid']);
                    </script>
                    <nav class="navbar navbar-light bg-light justify-content-start">
                        <a href="<?= $grid->filter('type', 'eq', '', false) ?>"
                           class="btn <?= (null === $grid->getFilter('type', 'eq') ? 'btn-info' : 'btn-secondary') ?>"
                           data-ajax>
                            <?= __('All') ?>
                        </a>
                        <a href="<?= $grid->filter('type', 'eq', Table::TYPE_DEBIT, false) ?>"
                           class="ms-2 btn <?= (Table::TYPE_DEBIT === $grid->getFilter('type', 'eq') ? 'btn-info' : 'btn-secondary') ?>"
                           data-ajax>
                            <?= __('Debit') ?>
                        </a>
                        <a href="<?= $grid->filter('type', 'eq', Table::TYPE_CREDIT, false) ?>"
                           class="ms-2 btn <?= (Table::TYPE_CREDIT === $grid->getFilter('type', 'eq') ? 'btn-info' : 'btn-secondary') ?>"
                           data-ajax>
                            <?= __('Credit') ?>
                        </a>
                    </nav>
                    <hr/>

                    <div class="d-none d-md-block">
                        <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
                        <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>
                    </div>

                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th width="80px">#</th>
                            <th width="80px"><a href="<?= $grid->order('amount') ?>"><?= __('Amount') ?></a></th>
                            <th></th>
                            <th width="180px" class="d-none d-lg-table-cell"><a href="<?= $grid->order('created') ?>"><?= __('Created') ?></a></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($grid->getData() as $i => $row) : /** @var \Application\Transactions\Row $row */?>
                            <tr>
                                <td class="align-middle"><?= $row->id ?></td>
                                <td class="text-right align-middle">
                                    <?= $row->getAmount() ?>
                                </td>
                                <td class="controls align-middle">
                                    <?php if ($row['carName']) : ?>
                                        <a href="<?= $this->url('cars', 'info', ['id' => $row['carId']]) ?>" class="btn btn-success btn-sm mr-1"
                                           data-ajax-dialog data-ajax-method="get">
                                            <i class="fa fa-car"></i>
                                        </a> <?= $row['carName'] ?>
                                    <?php elseif ($row['chargeName']) : ?>
                                        <a href="<?= $this->url('charges', 'info', ['id' => $row['chargeId']]) ?>" class="btn btn-light btn-sm mr-1"
                                           data-ajax-dialog data-ajax-method="get">
                                            <i class="fa fa-battery"></i></a>
                                        <?= $row['chargeName'] ?>
                                    <?php elseif ($row['money']) : ?>
                                        <a href="<?= $this->url('payments', 'info', ['id' => $row['paymentId']]) ?>" class="btn btn-warning btn-sm mr-1"
                                           data-ajax-dialog data-ajax-method="get">
                                            <i class="fa fa-dollar"></i></a>
                                        <?= $row['money'] ?> <?= $row['currency'] ?>
                                    <?php endif; ?>
                                </td>
                                <td class="d-none d-lg-table-cell align-middle"><?= $row->created ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                    <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
                    <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
                    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

                </div>


            </div>
        </div>
    </div>
</div>


