<?php
$this->addPartialPath(PATH_APPLICATION . '/modules/users/views/partial');
?>
<div class="card text-center">
  <?=$this->partial('card-header.phtml', ['user' => $user]) ?>
  <div class="card-body">
    <h4 class="card-title"><?= __('Wallet') ?></h4>
    <div class="card w-50 center">
      <div class="card-body">
        <ul class="list-group">
          <li class="list-group-item d-flex w-100 justify-content-between">
            <h6 class="mb-1"><?= __('Balance') ?></h6>
            <strong><?= $wallet->amount ?></strong>
          </li>
          <li class="list-group-item d-flex w-100 justify-content-between">
            <h6 class="mb-1"><?= __('Blocked') ?></h6>
            <strong><?= $wallet->blocked ?></strong>
          </li>
        </ul>
      </div>
      <div class="card-footer text-center">
        <a href="<?= $this->url('wallet', 'history')?>" class="btn btn-primary">
            <?= __('Transactions history') ?>
        </a>
      </div>
    </div>
  </div>
</div>
