<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
$uid = $grid->getUid();

use \Application\Transactions\Table;
?>
<div class="clearfix" data-spy="grid" data-grid="<?= $uid ?>">
  <script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
  </script>
  <nav class="navbar navbar-light bg-light justify-content-start">
      <a href="<?= $grid->filter('type', 'eq', '', false) ?>"
         class="btn btn-secondary <?= (null === $grid->getFilter('type', 'eq') ? 'btn-info' : '') ?>"
         data-ajax>
          <?= __('All') ?>
      </a>
      <a href="<?= $grid->filter('type', 'eq', Table::TYPE_DEBIT, false) ?>"
         class="ml-2 btn btn-secondary <?= (Table::TYPE_DEBIT === $grid->getFilter('type', 'eq') ? 'btn-info' : '') ?>"
         data-ajax>
          <?= __('Debit') ?>
      </a>
      <a href="<?= $grid->filter('type', 'eq', Table::TYPE_CREDIT, false) ?>"
         class="ml-2 btn btn-secondary <?= (Table::TYPE_CREDIT === $grid->getFilter('type', 'eq') ? 'btn-info' : '') ?>"
         data-ajax>
          <?= __('Credit') ?>
      </a>
  </nav>
  <hr/>

  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th width="80px">#</th>
      <th width="20px"></th>
      <th width="80px"><a href="<?= $grid->order('amount') ?>"><?= __('Amount') ?></a></th>
      <th></th>
      <th width="180px"><a href="<?= $grid->order('created') ?>"><?= __('Created') ?></a></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $i => $row) : /** @var \Application\Transactions\Row $row */?>
      <tr>
        <td><?= $row->id ?></td>
        <td>
            <?php if ($row->type === Table::TYPE_DEBIT) : ?>
              <i class="fa fa-plus" aria-hidden="true"></i>
            <?php elseif ($row->type === Table::TYPE_CREDIT): ?>
              <i class="fa fa-minus" aria-hidden="true"></i>
            <?php elseif ($row->type === Table::TYPE_BLOCK): ?>
              <i class="fa fa-lock" aria-hidden="true"></i>
            <?php elseif ($row->type === Table::TYPE_UNBLOCK): ?>
              <i class="fa fa-unlock-alt" aria-hidden="true"></i>
            <?php endif; ?>
        </td>
        <td><?= $row->amount ?></td>
        <td>
          <?php if ($user = $row->getChainUser()) : ?>
            <a href="<?= $this->url('users', 'profile', ['id' => $user->id]); ?>" class="btn btn-info" data-ajax-dialog
               data-ajax-method="get" data-modal-style="modal-lg">
              <i class="fa fa-id-card"></i> <?=$user->login?>
            </a>
          <?php endif; ?>
        </td>
        <td><?= $row->created ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

  <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

</div>