<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
$uid = $grid->getUid();

use \Application\Transactions\Table;
?>
<div class="clearfix" data-spy="grid" data-grid="<?= $uid ?>">
  <script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
  </script>
  <nav class="navbar navbar-light bg-light justify-content-start">
      <a href="<?= $grid->filter('type', 'eq', '', false) ?>"
         class="btn btn-secondary ajax <?= (null === $grid->getFilter('type', 'eq') ? 'btn-info' : '') ?>">
          <?= __('All') ?>
      </a>
      <a href="<?= $grid->filter('type', 'eq', Table::TYPE_DEBIT, false) ?>"
         class="ml-2 btn btn-secondary ajax <?= (Table::TYPE_DEBIT === $grid->getFilter('type', 'eq') ? 'btn-info' : '') ?>">
          <?= __('Debit') ?>
      </a>
      <a href="<?= $grid->filter('type', 'eq', Table::TYPE_CREDIT, false) ?>"
         class="ml-2 btn btn-secondary ajax <?= (Table::TYPE_CREDIT === $grid->getFilter('type', 'eq') ? 'btn-info' : '') ?>">
          <?= __('Credit') ?>
      </a>
  </nav>
  <hr/>

  <?= $this->partial("grid/total.phtml", ["grid" => $grid]) ?>
  <?= $this->partial("grid/limit.phtml", ["grid" => $grid]) ?>

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th width="80px">#</th>
      <th width="20px"></th>
      <th ><a href="<?= $grid->order('amount') ?>"><?= __('Amount') ?></a></th>
      <th width="180px"><a href="<?= $grid->order('created') ?>"><?= __('Created') ?></a></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $i => $row) : ?>
      <tr>
        <td><?= $row->id ?></td>
        <td>
            <?php if ($row->type === Table::TYPE_DEBIT) : ?>
              <i class="fa fa-plus" aria-hidden="true"></i>
            <?php else: ?>
              <i class="fa fa-minus" aria-hidden="true"></i>
            <?php endif; ?>
        </td>
        <td><?= $row->amount ?></td>
        <td><?= $row->created ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

  <?= $this->partial("grid/empty-rows.phtml", ["grid" => $grid]) ?>
  <?= $this->partial("grid/pagination.phtml", ["grid" => $grid]) ?>
  <?= $this->partial("grid/total.phtml", ["grid" => $grid]) ?>

</div>