<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
$uid = $grid->getUid();

use \Application\Transactions\Table;
?>

<script type="module">
  import '<?=$this->baseUrl('/js/bluz.grid.js');?>';
</script>

<div class="clearfix" data-spy="grid" data-grid="<?= $uid ?>">
  <nav class="navbar navbar-light bg-light justify-content-start">
      <a href="<?= $grid->filter('type', 'eq', '', false) ?>"
         class="btn <?= (null === $grid->getFilter('type', 'eq') ? 'btn-info' : 'btn-secondary') ?>"
         data-ajax>
          <?= __('All') ?>
      </a>
      <a href="<?= $grid->filter('type', 'eq', Table::TYPE_DEBIT, false) ?>"
         class="ms-2 btn <?= (Table::TYPE_DEBIT === $grid->getFilter('type', 'eq') ? 'btn-info' : 'btn-secondary') ?>"
         data-ajax>
          <?= __('Debit') ?>
      </a>
      <a href="<?= $grid->filter('type', 'eq', Table::TYPE_CREDIT, false) ?>"
         class="ms-2 btn <?= (Table::TYPE_CREDIT === $grid->getFilter('type', 'eq') ? 'btn-info' : 'btn-secondary') ?>"
         data-ajax>
          <?= __('Credit') ?>
      </a>
  </nav>
  <hr/>

  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th width="60px" class="text-center"><a href="<?= $grid->order('transactions.id') ?: '#' ?>"><?= __('Id') ?></a></th>
      <th width="180px"><a href="<?= $grid->order('users.login') ?>"><?= __('User') ?></a></th>
      <th width="180px"><a href="<?= $grid->order('usersChain.login') ?>"><?= __('Chain') ?></a></th>
      <th width="100px"><a href="<?= $grid->order('amount') ?>"><?= __('Amount') ?></a></th>
      <th></th>
      <th width="200px" class="d-none d-lg-table-cell"><a href="<?= $grid->order('created') ?>"><?= __('Created') ?></a></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $i => $row) : /** @var \Application\Transactions\Row $row */?>
      <tr>
        <td class="text-right"><?= $row->id ?></td>
        <td>
          <a href="<?=$this->url('users', 'profile', ['id' => $row->userId])?>"
             data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
              <?= $row->login ?>
          </a>
        </td>
        <td>
          <?php if ($row->chainUserId): ?>
          <a href="<?=$this->url('users', 'profile', ['id' => $row->chainUserId])?>"
             data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
              <?= $row->chainLogin ?>
          </a>
          <?php endif; ?>
        </td>
        <td class="text-right ">
          <?= $row->getAmountString() ?>
        </td>
        <td class="controls text-center ">

        </td>
        <td class="d-none d-lg-table-cell"><?= $row->created ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

  <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

</div>